# ─────────────────────────────────────────────────────────────
# Gradle Properties
# This file is used to define properties for the Gradle build system. It can be used to set project-wide properties, such as versions of dependencies, JVM arguments, and other configuration settings that will be applied to all subprojects in a multi-project build. In this file, we define the versions of Spring Boot and its dependency management plugin, as well as some Gradle and Java settings that will be used throughout the project.
# for Gradle properties, see https://docs.gradle.org/current/userguide/build_environment.html#gradle_properties
# ─────────────────────────────────────────────────────────────
springBootVersion=3.5.14
springBootDependencyManagementVersion=1.1.7

# ─────────────────────────────────────────────────────────────
# Gradle
# ─────────────────────────────────────────────────────────────
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false

# ─────────────────────────────────────────────────────────────
# Java
# ─────────────────────────────────────────────────────────────
javaVersion=21
