# ───────────────────────────────────────────────────────────────────────────────
# SSL configuration for development environment
# This configuration enable HTTPS for the application and configures
# the SSL context with a self-signed certificate located in the classpath.
# ───────────────────────────────────────────────────────────────────────────────
server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:certs/backend-dev.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: backend-dev

# ───────────────────────────────────────────────────────────────────────────────
# Proxy configuration for development environment.
# This configuration enables SSL for outgoing requests and configures
# the trust store with a self-signed certificate.
# ───────────────────────────────────────────────────────────────────────────────
proxy:
  endpoint-query-param: endpoint
  ssl:
    enabled: true
    trust-store: classpath:certs/dev-truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
    # insecure-trust-all: true

# ───────────────────────────────────────────────────────────────────────────────
spring:
  main:
    lazy-initialization: true
  application:
    name: oauth-proxy-gateway

# ───────────────────────────────────────────────────────────────────────────────
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"